### ISSUE TITLE
replace auto-generated package.json files with pnpm-lock.yaml files

### ISSUE THREAD

**Issue by matthewbub** [matthewbub/calendar-widgets#46]
This ticket is a continuation of **use pnpm instead of npm #38**

## Tasks 
- [x] Delete all instances of `package-lock.json` files 
- [x] Add the auto generated `pnpm-lock.yaml` files to each corresponding directory 
- [x] Add `package-lock.json` to the root `.gitignore` to avoid future confusion
